name: Radios
version: '${project.version}'
main: it.naick.radios.Radios
api-version: 1.16
authors: [ Naick ]
commands:
  radio:
    aliases:
      - radios
    permission: radios.admin
    permission-message: "ยง4|ยงc Non hai i permessi per utilizzare questo comando"
